site_name: Ricardo Breindembache
site_url: https://ricardobrein.github.io
site_author: Ricardo Brein🧠
site_description: >
   Inteligencia Artificial - Machine Learning - Data Science - Big Data - Deep Learning - Self-Taught

repo_name: Ricardobrein/ricardobrein.github.io
repo_url: https://github.com/ricardobrein
repo_name: ricardobrein.github.io

theme:
  name: material
  custom_dir: docs/assets/
  font:
    text: Fira Sans
    code: Roboto mono
  language: es
  logo: images/yo.png
  icon:
    repo: fontawesome/brands/github
    book: fontawesome/solid/book
  palette:
    - scheme: default
      primary: amber
      accent: light blue
      toggle:
        icon: material/weather-night
        name: dark
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: light
  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.follow
    - content.tabs.link
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotations
markdown_extensions:
  - toc:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
  # ... other extensions ...

# Extra content
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ricardobrein
      name: GitHub - RicardoBrein
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ricardo-breindembache/
      name: LinkedIn - Ricardo Breindembache 
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ricardobreindembache@gmail.com>
      name: Email - Ricardo Breindembache
    - icon: fontawesome/brands/medium
      link: https://medium.com/@ricardobrein
      name: Medium @Ricardobrein
    - icon: fontawesome/brands/hashnode
      link: ricardobrein.hashnode.dev
      name: hashnode Blog

# Navigation menu
nav:
  - Hola👋: index.md
  - About me.: about.md
  - Tech Stack: stack.md
  - Certificaciones: certifications.md
  - Projects: projects.md
  - Blog: 
    - blog/index.md

extra_css:
  - docs/assets/custom.css

# Plugins
plugins:
  - mkdocs-jupyter:
      theme: dark
  - tags
  - search